### PR TITLE
Update Italian language

### PR DESCRIPTION
**Pull request by bovirus**
@Timthreetwelve 

Please merge. Thanks.

### CODE REVIEW

**Review by Timthreetwelve — APPROVED** [review]

**Comment by Timthreetwelve** [comment]
Thank you!

**Comment by CMTriX** [comment]
dutch also ready for merging!

**Comment by Timthreetwelve** [comment]
@CMTriX

I've removed ipext.org as a provider. Would you please update these two keys in Strings.nl-NL.xaml based on the text in the en-US file?

- SettingsItem_PublicInfoProviderTooltipLine1
- SettingsItem_PublicInfoProviderTooltipLine2

And delete this key.

- SettingsEnum_Provider_IpExtOrg

Thanks,
Tim

**Comment by Timthreetwelve** [comment]
@CMTriX

Thanks, you are quick! 

Tim

**Pull request merged**
