### PR TITLE
Update Italian language and installer script improvement

### PR DESCRIPTION
**Pull request by bovirus**
@Timthreetwelve 

Please check and merge. Thanks.

### CODE REVIEW

**Review by Timthreetwelve — APPROVED** [review]
Thanks!

**Comment by Timthreetwelve** [comment]
I've created a [repo](https://github.com/Timthreetwelve/Setup_Common) specifically for the Inno Setup files common to my various projects. This will allow PR's for the individual language files and reduces duplicating of effort. 😁

I'll make the necessary changes in my projects as time permits.

**Comment by bovirus** [comment]
@Timthreetwelve

My personal sugegstion is not mix standard .isl file (standard with Inno Setup) with custom strings for your program.

My suggestion is publish only custom messages and not strandrd isl that you get from standard Inno Setup installation.

You can make all language and custom messahes in a separate Inno Setup script and use include to import it in main script.

If you like I can explain with a PR.

**Comment by bovirus** [comment]
Example of file "GetMyIP.Localization.iss"

[Languages]
Name: "en"; MessagesFile: "compiler:\Default.isl"
Name: "ca"; MessagesFile: "compiler:\Languages\Catalan.isl"
Name: "de"; MessagesFile: "compiler:\Languages\German.isl"
Name: "es"; MessagesFile: "compiler:\Languages\Spanish.isl"
Name: "fr"; MessagesFile: "compiler:\Languages\French.isl"
Name: "it"; MessagesFile: "compiler:\Languages\Italian.isl"
Name: "nl"; MessagesFile: "compiler:\Languages\Dutch.isl"
Name: "uk"; MessagesFile: "compiler:\Languages\Ukrainian.isl"

[LangOptions]
DialogFontSize=9
DialogFontName="Segoe UI"
WelcomeFontSize=14
WelcomeFontName="Segoe UI"

[CustomMessages]
en.ViewReadme=View the ReadMe file
wn.AppIsRunning=is running, please close it to continue with the installation.
en.DeleteConfigFiles=Do you want to remove the settings files?%nSelect 'No' if you plan on reinstalling.

ca.ViewReadme=Veure el fitxer RadMe
ca.AppIsRunning=s'està executant, tanqueu-lo per continuar amb la instal·lació.
ca.DeleteConfigFiles=Voleu eliminar la configuració i excloure fitxers? Seleccioneu 'No' si teniu previst tornar a instal·lar.

de.ViewReadme=Lesen Sie die ReadMe-Datei
de.AppIsRunning=ausgeführt wird, schließen Sie es bitte, um mit der Installation fortzufahren.
de.DeleteConfigFiles=Möchten Sie die Einstellungen und Ausschlussdateien entfernen? Wählen Sie 'Nein', wenn Sie eine Neuinstallation planen.

;es.ViewReadm=
;es.AppIsRunning=
;es.DeleteConfigFiles=

fr.ViewReadme=Voir le fichier ReadMe
fr.AppIsRunning=est en cours d'exécution, veuillez le fermer pour poursuivre l'installation.
fr.DeleteConfigFiles=Voulez-vous supprimer les paramètres et les fichiers d'exclusion ? Sélectionnez 'Non' si vous prévoyez de réinstaller.

it.ViewReadme=Visualizza file ReadMe
it.AppIsRunning=è in esecuzione.%nChiudilo per continuare l'installazione.
it.DeleteConfigFiles=Vuoi rimuovere le impostazioni e i file di esclusione?%nSeleziona 'No' se vuoi reinstallare il programma più avanti. 

nl.ViewReadme=Open de ReadMe file
nl.AppIsRunning=wordt uitgevoerd, sluit deze dan af om door te gaan met de installatie.
nl.DeleteConfigFiles=Wil je de instellingen en uitsluitingsbestanden verwijderen? Selecteer 'Nee' als je van plan bent om opnieuw te installeren.

;uk.ViewReadm=
;uk.AppIsRunning=
;uk.DeleteConfigFiles=

I cannot put es/uk string because is coded not as UTF.8 in sepaarte repository.

note

use of "compiler:" for stabndard isl language file
use of "%n" for new line in custom string.

in this case in main script just add

#include "GetMyIP.Localization.iss"

**Comment by Timthreetwelve** [comment]
Okay, now I'm beginning to understand. The adding the #include statement in the main script file was the part that I wasn't visualizing.

Do you have any ideas of how to get the version number in the window title without modifying SetupWindowTitle?

**Comment by Timthreetwelve** [comment]
I think I've got it.

Would you check GetMyIP.iss and GetMyIPLocalization.iss? https://github.com/Timthreetwelve/GetMyIP/tree/main/GetMyIP/Inno_Setup

**Comment by bovirus** [comment]
@Timthreetwelve 

I revsied the file that you mentioned (I just added %n in some strings) and also README license.

Pelase check and merge this PR https://github.com/Timthreetwelve/GetMyIP/pull/31

Note;: when I edited the file in GetMyIP github repsoitory it mentioend that liene ending is diferrent between Windows and github.
If I do the same job in WUView github repository and didn't get any warning.
See screenshot

image

Please check settings of two your repsoitory.

Please check also my pending request in WUView repository,

**Pull request merged**
