### PR TITLE
Add Italian language

### PR DESCRIPTION
**Pull request by bovirus**
@Timthreetwelve 

Please check and merge, Thanks.

### CODE REVIEW

**Comment by bovirus** [comment]
Add also Dutch language

**Review by Timthreetwelve — APPROVED** [review]
@bovirus Thank you so much for the translation. Thanks also for including the Dutch translation from @CMTriX in the PR.

I'm going to approve and merge tonight. However, there are a couple of issues.
1. I left out a couple of the `xml:space` tags. I will fix these in each language file after the merge.
2. While working on the project the last few days I've added about 5 strings and updated 2 more. 

Tim

**Comment by Timthreetwelve** [comment]
@bovirus and @CMTriX I have both the Italian and Dutch files working in the app. There are UI tweaks needed, such as buttons and other controls to narrow to accommodate the longer text, a weird alignment problem, and for some reason the tooltip for the tray icon is 0 bytes in Italian and Dutch. It's been a long day, my eyes are tired, so I'll pick this up in the morning.

I did get the missing tags added to the language files and pushed back to GitHub. Also, I keep forgetting to ask, on the External IP page, is there a word for State that would be more appropriate for your locality?

Thanks,
Tim

**Comment by bovirus** [comment]
@Timthreetwelve

No problem.
Please ad dnew strings and I will update it.
I'm working on Inno Setup Installer script.

**Comment by CMTriX** [comment]
Please add new strings and I will update it too.

**Comment by CMTriX** [comment]
-State- / Provincie 

In the Netherlands we don't have states.

**Comment by Timthreetwelve** [comment]
@CMTriX 

These 2 strings were updated:

``` XML
<sys:String x:Key="MsgText_Error_JsonNull" xml:space="preserve">JSON file is null.&#13;Please consider opening an issue and attaching the log file.</sys:String>
<sys:String x:Key="MsgText_Error_JsonParsing" xml:space="preserve">Error parsing JSON.&#13;{0}&#13;Please consider opening an issue and attaching the log file.</sys:String>
```

These are new:

``` XML
<sys:String x:Key="SettingsItem_PublicInfoProvider">External IP information provider</sys:String>
<sys:String x:Key="SettingsItem_PublicInfoProviderTooltip" xml:space="preserve">ip-api.com provides full details&#13;ipext.org provides IP address only</sys:String>

<sys:String x:Key="SettingsEnum_Provider_IpApiCom">ip-api.com</sys:String>
<sys:String x:Key="SettingsEnum_Provider_IpExtOrg">ipext.org</sys:String>

<sys:String x:Key="SettingsItem_ObfuscateLog">Obfuscate IP details in log file</sys:String>

<sys:String x:Key="About_Contribute">Contribute</sys:String>
<sys:String x:Key="About_ContributeToolTip">How to contribute a translation</sys:String>
```

**Comment by CMTriX** [comment]
<sys:String x:Key="SettingsItem_PublicInfoProvider">Externe IP informatie provider</sys:String>
<sys:String x:Key="SettingsItem_PublicInfoProviderTooltip" xml:space="preserve">ip-api.com levert uitgebreide details&#13;ipext.org levert alleen het IP adres</sys:String>

<sys:String x:Key="SettingsEnum_Provider_IpApiCom">ip-api.com</sys:String>
<sys:String x:Key="SettingsEnum_Provider_IpExtOrg">ipext.org</sys:String>

<sys:String x:Key="SettingsItem_ObfuscateLog">Verberg IP details in het logbestand</sys:String>

<sys:String x:Key="About_Contribute">Bijdrage</sys:String>
<sys:String x:Key="About_ContributeToolTip">Hoe kan ik een vertaling bijdragen?</sys:String>

**Comment by Vaso73** [comment]
Hallo Tim..., I created a new translation of Slovak lang. (sk-SK) how to add it to the ground???

**Comment by bovirus** [comment]
@Vaso73

Make a clone of the repository. Then create a PR with your language.

Or post here your file. And I can do it.

**Comment by Vaso73** [comment]
I send file...
[Strings.sk-SK.zip](https://github.com/Timthreetwelve/GetMyIP/files/13203177/Strings.sk-SK.zip)

**Comment by bovirus** [comment]
@Vaso73

Please translate the strings (test after =) in your language.

ViewReadme=View the ReadMe file
AppIsRunning=is running, please close it to continue with the installation.
DeleteConfigFiles=Do you want to remove the settings files?%n%nSelect 'No' if you plan on reinstalling.

**Comment by Vaso73** [comment]
Hallo, where download full version strings for translate?, I use portable(no install) version...

**Comment by bovirus** [comment]
@Vaso73 

Please conftrm the strings for installer.

The language file are here.

https://github.com/Timthreetwelve/GetMyIP/tree/main/GetMyIP/Languages

please check and update your Slovak language using as base for compare master English language

https://github.com/Timthreetwelve/GetMyIP/blob/main/GetMyIP/Languages/Strings.en-US.xaml

@Timthreetwelve 

if you are agrre i think to close this ticket and open a new with a title like

"Ccontribute about translation"

**Comment by Timthreetwelve** [comment]
@bovirus 

I'm just starting my day here and I see that you've been busy. 😃

Yes, please create a new issue for this. We shouldn't be adding to issues/PRs that have been closed/merged anyway, it makes it difficult for me find the new comments. 

I like the idea of the application name being inside the comment block at the top of the language files. 👍🏻 I pushed an update to Strings.en-US.

I'll be back later today.

**Pull request merged**
