### PR TITLE
Add Korean

### PR DESCRIPTION
**Pull request by VenusGirl**

### CODE REVIEW

**Review by VenusGirl — COMMENTED** [review]
Add Korean...

**Review by Timthreetwelve — APPROVED** [review]
@VenusGirl Thank you so much for submitting this PR. This is the first non-Latin language I've had the opportunity to work with. Consequently, I hope that you won't mind if I ask some questions.

Tim

**Comment by VenusGirl** [comment]
Yes, ask me anything...

**Comment by Timthreetwelve** [comment]
Thanks. When I check a new language one of the things that I look for is to see that none of the phrases are cut truncated or otherwise displayed incorrectly. I didn't notice any, and Korean phrases generally appear to be shorter than English, so I don't anticipate any. 

In the screenshot below, the word "Get" appears missing (in the green box). Or am I misinterpreting?
The resource string in English is `<sys:String x:Key="About_Update">Update Get My IP</sys:String>`.

Also, could you verify that I have attributed your contribution correctly (in the blue box).

GetMyIP_2024-06-23_21-26-42

I'll look at the Inno Setup updates tomorrow, it's getting late here. 😴

Thanks again,
Tim

**Comment by VenusGirl** [comment]
I added the missing "Get" with the green mark
The name of the contributor in the blue mark is correct: English (Korean)
The language name is written in English, but is it automatically translated because the country (language) code is applied?
Do I have to write only one contributor's name?

**Comment by VenusGirl** [comment]
OKI understand.

**Pull request merged**
